### PR TITLE
Feature/feedback consistency

### PR DESCRIPTION
**Pull request by bigultekin**
**Feature:**

1. Gets feedback and the submission text blocks they belong to
2. Segments the feedback comments
3. Calculates embeddings for each feedback comment text block
4. Checks consistencies of the added feedback (There should be at least one feedback comment with same cluster ids in the database)
5. Stores feedback and related information in the database(if the feedback is updated, db is also updated)
6. Returns inconsistencies

- I changed the segmentation request a bit for segmenting feedback comments. It shouldn't affect the other requests for the submissions.
- It is possible to get the data from .csv to test the functionality. 

**How To Test:** (2 options)

Test with CSV File:

- It is possible to test the functionality with a csv file. Just ask me one!
- You might need to install some libraries in the benchmark folder

1.  Put csv file to resources folder in the benchmark folder 
2. Build and start the docker
3. Run the main.py
4. It will take a little time then inconsistencies will be written to another csv file. 

Test with Artemis:

- Follow the steps for testing in this [PR](https://github.com/ls1intum/Artemis/pull/1977) in Artemis.

### CODE REVIEW

**Comment by linusmichel** [comment]
Could you add some instructions on how to test your changes to this PR?

**Comment by bigultekin** [comment]
> Could you add some instructions on how to test your changes to this PR?

It is better to test it with a PR that I will create in Artemis in few days. It is not worth the effort now :)

**Review by CanArisan — DISMISSED** [review]
Works as described, nice work!

**Review by CanArisan — APPROVED** [review]
Reapprove

**Review by jpbernius — APPROVED** [review]

**Pull request merged**
